cache_config:
  cache: True
  caching_strategy: exact  # alternative: similarity
  cache_db_version: 0.1
  url: null

feedback: False

model_config:
  open_ai_key: <OPENAI API KEY>
  model: open_ai_model
  model_name: gpt-4
  max_tokens: 2500

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
